In [3]:
# Библиотека Numpy
import numpy as np

# Example code

### Примеры матриц:

In [63]:
# Массив 2D 
arr2D = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

print("- Двухмерный массив:")
print(arr2D)

- Двухмерный массив:
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [85]:
# Вектор
print("- Вектор:")
print("  1) Вектор-строка:")
print("    np.narray([1,2,3,4]) = \n", np.array([1,2,3,4]), end="\n\n")
print("  2) Вектор-столбец:")
print("    np.narray([1,2,3,4]) = \n", np.array([[1],[2],[3],[4]]), end="\n\n")
print("  3) Нулевой:")
print("    3.1) Вектор строка:")
print("      np.zeros((4)) = \n", np.zeros((4)), end="\n\n")
print("    3.2) Вектор столбец:")
print("      np.zeros((4)) = \n", np.zeros((4, 1)), end="\n\n")
print("  4) Единичный:")
print("    4.1) Вектор строка:")
print("      np.zeros((4)) = \n", np.ones((4)), end="\n\n")
print("    4.2) Вектор столбец:")
print("      np.zeros((4)) = \n", np.ones((4, 1)), end="\n\n")

# Матрица
print("- Квадратнаяы матрица:")
print("  1) Создать:")
print("    1.1) Квадратную матрицу с помощью метода array():")
print("      np.narray([[1, 2], [3, 4]]) = \n", np.array([[1, 2], [3, 4]]), end="\n\n")
print("    1.2) Отдельно и передать в функцию:")
print("      np.narray(arr2D) = \n", np.array(arr2D), end="\n\n")
print("    1.3) Построение объекта типа matrix с помощью одноименного метода:")
print("      np.matrix([[1, 2], [3, 4]]) = \n", np.matrix([[1, 2], [3, 4]]), end="\n\n")
print("    1.4) Доступен стиль Matlab, когда между элементами ставятся пробелы, а строки разделяются точкой с запятой:")
print("      np.matrix(\"1 2 3; 4 5 6; 7 8 9\") = \n", np.matrix("1 2 3; 4 5 6; 7 8 9"), end="\n\n")

# Диагональная
print("- Диагональная матрица:")
print("  1) Построить вручную, задав только значения элементам на главной диагонали:")
print("      np.matrix([[1, 0], [0, 1]]) = \n", np.matrix([[1, 0], [0, 1]]), end="\n\n")
print("  2) Извлечем ее главную диагональ:")
print("      np.diag(np.matrix('1 2 3; 4 5 6; 7 8 9')) = \n", np.diag(np.matrix('1 2 3; 4 5 6; 7 8 9')), end="\n\n")
print("  3) Построим диагональную матрицу на базе полученной диагонали:")
print("      np.diag(np.matrix('1 2 3; 4 5 6; 7 8 9')) = \n", np.diag(np.diag(np.matrix('1 2 3; 4 5 6; 7 8 9'))), end="\n\n")

# Единичная (диагональ)
print("- Единичная матрица:")
print("  1) Создать Единичная матрица на базе списка и передадим в качестве аргумента функции matrix():")
print("      np.matrix([[1, 0], [0, 1]]) = \n", np.matrix([[1, 0], [0, 1]]), end="\n\n")
print("  2) Для построения такого типа матриц в библиотеке Numpy есть специальная функция – eye():")
print("      np.eye(2) = \n", np.eye(2), end="\n\n")
print("  3) Можно получить с помощью функции identity():")
print("      np.identity(2) = \n", np.identity(2), end="\n\n")

# Нулевая (диагональ)
print("- Нулевая матрица:")
print("  1) Создать матрица и заполняет число ноль - zeros():")
print("      np.zeros((3, 3)) = \n", np.zeros((3, 3)), end="\n\n")

# Задание матрицы в общем виде
print("- Задание матрицы в общем виде:")
print("  1) Если есть данные о содержимом матрицы, то создать ее можно используя списки:")
print("      np.matrix('1 2 3 4; 5 6 7 8') = \n", np.matrix('1 2 3 4; 5 6 7 8'), end="\n\n")
print("  2) Cоздать матрицу заданного размера с произвольным содержимым:")
print("      np.zeros((3, 5)) = \n", np.zeros((3, 5)), end="\n\n")

# Транспонирование
print("- Транспонирование матрицы:")
print("  1) Транспонируем матрицу с помощью метода transpose():")
print("      np.matrix('1 2 3 4; 5 6 7 8').transpose() = \n", np.matrix('1 2 3 4; 5 6 7 8').transpose(), end="\n\n")
print("  2) Можно сокращенный вариант:")
print("      np.matrix('1 2 3 4; 5 6 7 8').T = \n", np.matrix('1 2 3 4; 5 6 7 8').T, end="\n\n")
print("  C) Свойство:")
print("      1) Дважды транспонированная матрица равна исходной матрице:")
print("      (np.matrix('1 2 3 4; 5 6 7 8').T).T = \n", (np.matrix('1 2 3 4; 5 6 7 8').T).T, end="\n\n")
print("      2) Транспонирование суммы матриц равно сумме транспонированных матриц:")
print("      (np.matrix('1 2 3; 4 5 6') + np.matrix('7 8 9; 10 11 12')).T = \n", (np.matrix('1 2 3; 4 5 6') + np.matrix('7 8 9; 10 11 12')).T, end="\n\n")
print("      3) Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:")
print("      (np.matrix('1 2 3; 4 5 6').dot(np.matrix('7 8 9; 10 11 12'))).T = \n", (np.matrix('1 2 3; 4 5 6').dot(np.matrix('7 8; 9 10; 11 12'))).T, end="\n\n")
print("      4) Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:")
print("      (np.matrix('1 2 3; 4 5 6') * 3).T = \n", (np.matrix('1 2 3; 4 5 6') * 3).T , end="\n\n")
print("      5) Определители исходной и транспонированной матрицы совпадают:")
print("      format( np.linalg.det(np.matrix('1 2; 3 4')), '.9g') = \n", format( np.linalg.det(np.matrix('1 2; 3 4')), '.9g') , end="\n\n")

# Действия над матрицами
print("- Транспонирование матрицы:")
print("  C) Свойство:")
print("      1) Произведение единицы и любой заданной матрицы равно заданной матрице:")
print("      1 * np.matrix('1 2; 3 4') = \n", 1 * np.matrix('1 2; 3 4'), end="\n\n")
print("      2) Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:")
print("      0 * np.matrix('1 2; 3 4') = \n", 0 * np.matrix('1 2; 3 4'), end="\n\n")
print("      3) Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:")
print("      (2 + 3) * np.matrix('1 2; 3 4') = \n", (2 + 3) * np.matrix('1 2; 3 4'), end="\n\n")
print("      4) Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:")
print("      (2 * 3) * np.matrix('1 2; 3 4') = \n", (2 * 3) * np.matrix('1 2; 3 4'), end="\n\n")
print("      5) Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:")
print("      3 * (np.matrix('1 2; 3 4') + np.matrix('5 6; 7 8')) = \n", 3 * (np.matrix('1 2; 3 4') + np.matrix('5 6; 7 8')), end="\n\n")

# Сложение матриц
print("- Сложение матриц:")
print("  C) Свойство:")
print("      1) Коммутативность сложения. От перестановки матриц их сумма не изменяется:")
print("      np.matrix('1 2; 3 4') + np.matrix('5 6; 7 8') = \n", np.matrix('1 2; 3 4') + np.matrix('5 6; 7 8'), end="\n\n")
print("      2) Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:")
print("      (np.matrix('1 2; 3 4') + np.matrix('5 6; 7 8')) + np.matrix('9 10; 11 12') = \n", (np.matrix('1 2; 3 4') + np.matrix('5 6; 7 8')) + np.matrix('9 10; 11 12'), end="\n\n")
print("      3) Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрице:")
print("      np.matrix('1 2; 3 4') + (-1) * np.matrix('5 6; 7 8') = \n", np.matrix('1 2; 3 4') + (-1) * np.matrix('5 6; 7 8'), end="\n\n")

# Умножение матриц
print("- Умножение матриц:")
print("  C) Свойство:")
print("      1) Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:")
print("      np.matrix('1 2; 3 4').dot(np.matrix('5 6; 7 8')).dot(np.matrix('9 10; 11 12')) = \n", np.matrix('1 2; 3 4').dot(np.matrix('5 6; 7 8')).dot(np.matrix('9 10; 11 12')), end="\n\n")
print("      2) Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:")
print("      np.matrix('1 2; 3 4').dot(np.matrix('5 6; 7 8')) + np.matrix('1 2; 3 4').dot(np.matrix('9 10; 11 12')) = \n", np.matrix('1 2; 3 4').dot(np.matrix('5 6; 7 8')) + np.matrix('1 2; 3 4').dot(np.matrix('9 10; 11 12')), end="\n\n")
print("      3) Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:")
print("      np.matrix('1 2; 3 4') + (-1) * np.matrix('5 6; 7 8') = \n", np.matrix('1 2; 3 4') + (-1) * np.matrix('5 6; 7 8'), end="\n\n")
print("      4) Произведение заданной матрицы на единичную равно исходной матрице:")
print("      np.matrix('1 0; 0 1').dot(np.matrix('1 2; 3 4')) = \n",  np.matrix('1 0; 0 1').dot(np.matrix('1 2; 3 4')), end="\n\n")
print("      4) Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:")
print("      np.matrix('0 0; 0 0').dot(np.matrix('1 2; 3 4')) = \n",  np.matrix('0 0; 0 0').dot(np.matrix('1 2; 3 4')), end="\n\n")

# Определитель матрицы
print("- Определитель матрицы:")
print("  1) Транспонируем матрицу с помощью метода transpose():")
print("      np.linalg.det(np.matrix('-4 -1 2; 10 4 -1; 8 3 1')) = \n",  "%.2f" % np.linalg.det(np.matrix('-4 -1 2; 10 4 -1; 8 3 1')), end="\n\n")
print("  C) Свойство:")
print("      1) Ассоциативность умножения. \n         Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:")
print("      round(np.linalg.det(np.matrix('-4 -1 2; 10 4 -1; 8 3 1')), 3) = \n", round(np.linalg.det(np.matrix('-4 -1 2; 10 4 -1; 8 3 1')), 3), end="\n\n")
print("      2) Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:")
print("      np.linalg.det(np.matrix('-4 -1 2; 0 0 0; 8 3 1')) = \n", np.linalg.det(np.matrix('-4 -1 2; 0 0 0; 8 3 1')), end="\n\n")
print("      3) При перестановке строк матрицы знак ее определителя меняется на противоположный:")
print("      np.linalg.det(np.matrix('-4 -1 2; 0 0 0; 8 3 1')) = \n", round(np.linalg.det(np.matrix('-4 -1 2; 10 4 -1; 8 3 1')), 3), end="\n\n")
print("      4) Если матрица содержит пропорциональные строки, то ее определитель равен нулю:")
print("      2 * np.matrix('-4 -1 2; 10 4 -1; 8 3 1')[0, :] = \n", 2 * np.matrix('-4 -1 2; 10 4 -1; 8 3 1')[0, :], end="\n\n")

# Обратная матрица
print("- Обратная матрица:")
print("  1) обратной матрицы будем использовать функцию *inv()*:")
print("      np.linalg.inv(np.matrix('1 -3; 2 5')) = \n", np.linalg.inv(np.matrix('1 -3; 2 5')), end="\n\n")
print("  C) Свойство:")
print("      1) Обратная матрица обратной матрицы есть исходная матрица:")
print("      np.linalg.inv(np.linalg.inv(np.matrix('1. -3.; 2. 5.'))) = \n", np.linalg.inv(np.linalg.inv(np.matrix('1. -3.; 2. 5.'))), end="\n\n")
print("      2) Обратная матрица обратной матрицы есть исходная матрица:")
print("      (np.linalg.inv(np.matrix('1. -3.; 2. 5.'))).T = \n", (np.linalg.inv(np.matrix('1. -3.; 2. 5.'))).T, end="\n\n")
print("      3) Обратная матрица произведения матриц равна произведению обратных матриц:")
print("      np.linalg.inv(np.matrix('7. 6.; 1. 8.')).dot(np.linalg.inv(np.matrix('1. -3.; 2. 5.'))) = \n", np.linalg.inv(np.matrix('7. 6.; 1. 8.')).dot(np.linalg.inv(np.matrix('1. -3.; 2. 5.'))), end="\n\n")
     
# Ранг матрицы
print("- Ранг матрицы:")
print("  x1) Использует функция matrix_rank():")
print("      np.linalg.matrix_rank(np.eye(7)) = \n", np.linalg.matrix_rank(np.eye(7)), end="\n\n")





- Вектор:
  1) Вектор-строка:
    np.narray([1,2,3,4]) = 
 [1 2 3 4]

  2) Вектор-столбец:
    np.narray([1,2,3,4]) = 
 [[1]
 [2]
 [3]
 [4]]

  3) Нулевой:
    3.1) Вектор строка:
      np.zeros((4)) = 
 [0. 0. 0. 0.]

    3.2) Вектор столбец:
      np.zeros((4)) = 
 [[0.]
 [0.]
 [0.]
 [0.]]

  4) Единичный:
    4.1) Вектор строка:
      np.zeros((4)) = 
 [1. 1. 1. 1.]

    4.2) Вектор столбец:
      np.zeros((4)) = 
 [[1.]
 [1.]
 [1.]
 [1.]]

- Квадратнаяы матрица:
  1) Создать:
    1.1) Квадратную матрицу с помощью метода array():
      np.narray([[1, 2], [3, 4]]) = 
 [[1 2]
 [3 4]]

    1.2) Отдельно и передать в функцию:
      np.narray(arr2D) = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

    1.3) Построение объекта типа matrix с помощью одноименного метода:
      np.matrix([[1, 2], [3, 4]]) = 
 [[1 2]
 [3 4]]

    1.4) Доступен стиль Matlab, когда между элементами ставятся пробелы, а строки разделяются точкой с запятой:
      np.matrix("1 2 3; 4 5 6; 7 8 9") = 